name: ar_animal_zoo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- AI & Camera ---
  flutter_vision: ^1.1.4
  camera: ^0.10.5+9

  # --- AR ---
  ar_flutter_plugin: ^0.7.3

  # --- Tiện ích ---
  audioplayers: ^5.2.1
  # Dùng bản mới nhất để fix lỗi Registrar
  permission_handler: ^11.3.0
  get: ^4.6.6
  vector_math: ^2.1.4
  image_picker: ^1.2.1
  path_provider: ^2.1.5

  # Firebase packages - Phiên bản ổn định
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.0
  http: ^1.1.0
  geolocator: ^9.0.2
  cached_network_image: ^3.3.0 # Để load ảnh từ internet (tin tức) mượt hơn
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.0
  google_generative_ai: ^0.4.6
# QUAN TRỌNG: Thêm đoạn này để ép dùng bản mới
dependency_overrides:
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
    
flutter_launcher_icons:
  android: "ic_launcher" # Tên file icon cho Android
  ios: true 
  image_path: "assets/images/ar_zoo_icon.png" 
  min_sdk_android: 21 # Khuyến nghị để hỗ trợ adaptive icon tốt hơn trên Android mới

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/audio/
    - assets/tflite/
    - assets/images/
